### PR TITLE
Issue 138 ✨ feature add status bar or other indicator when sending lots of assets to show the progress

### LINKED ISSUE #138: ✨ Feature: Add status bar or other indicator when sending lots of assets to show the progress
# ℹ Overview

When you send to lots of addresses it takes a while. There should be some sort of status indicator.

The status should be broken up into 4 stages: 
1) Looking up wallet balances & signing logical signatures
2) Sending transactions to the MyAlgo Connect bridge for signing
3) waiting for user signature via the MyAlgo GUI
4) sending the transactions to the recipients on the blockchain

### PR DESCRIPTION
**Pull request by treasurechic**
# ℹ Overview

### 📝 Related Issues

closes #138

### CODE REVIEW

File: components/SendAssetProgress.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
+import React, { useEffect, useState } from 'react'
+import PropTypes from 'prop-types'
+import { LinearProgressWithLabel } from './LinearProgressWithLabel'
+
+const SendAssetProgress = ({ progress }) => {
```
Comment (PhearZero) [inline components/SendAssetProgress.js]: This component shouldn't be necessary, use `<LinearProgressWithLabel>` directly and emit the `progress`, `status` and `total` as a part of the event

File: hooks/useSendAsset.js [hunk 2]
```diff
@@ -0,0 +1,19 @@
+import {useCallback, useEffect, useState} from 'react'
+import events from '../lib/events'
+function useSendAsset(){
+  const [progress, setProgress] = useState('uninitialized')
```
Comment (PhearZero) [inline hooks/useSendAsset.js]: - [x] Revert this back to `status` and use another state for `progress` that has a initial state of `0`.  
- [x] Introduce a new state called `total` which is a number with a initial state of 0. 
- [x] Introduce a new state called `hideProgress` with an effect that sets the value based on state

File: components/LinearProgressWithLabel.js [hunk 3]
```diff
@@ -0,0 +1,39 @@
+import React from 'react'
+import LinearProgress from '@mui/material/LinearProgress'
+import Typography from '@mui/material/Typography'
+import Box from '@mui/material/Box'
+import PropTypes from 'prop-types'
+
+export const LinearProgressWithLabel = (props) => {
+  const { value, report } = props
```
Comment (PhearZero) [inline components/LinearProgressWithLabel.js]: The progress bar should consume the payload from the event without any Wrappers like `<SendAssetProgress>`

- [x] Refactor `value` to `progress` since we have two components, it's not clear what the value is for
- [x] Refactor `report` to `status` to keep a consistent naming with the event payload.
- [x] Introduce `hideProgress`
- [x] Introduce `total` for sizing the progress.
   - [x] Normalize `value` for the `total` https://mui.com/material-ui/react-progress/#non-standard-ranges
- [x] Have at least one required property, component should not be able to return an empty fragment.

File: hooks/useSendAsset.js [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+    setProgress(_status)
+  },[setProgress])
+
+  useEffect(()=>{
+    events.on('sending-assets-event', onSendAsset)
+
+    return ()=> events.off('sending-assets-event')
+  }, [onSendAsset])
+
+  return {progress}
```
Comment (PhearZero) [inline hooks/useSendAsset.js]: Return `progress`, `status`, `hideProgress` and `total`

File: lib/helper.js [hunk 5]
```diff
@@ -158,6 +158,7 @@ const Helper = {
     events.emit('sign-with-my-algo', {status: 'signed'})
     console.debug({ signedTxnsFromUser })
     //const outerGroupTo
+    events.emit('sending-assets-event', {status: 'signing2'})
```
Comment (PhearZero) [inline lib/helper.js]: - [x] scope the events based on the work that they are doing . These events should be called `sign-with-my-algo`
- [x] signing2 is an unnecessary emit, we have already emitted `signed` at this point and there is no work done between the two events.
- [x] Emit the progress, status and total from after the signLogicSigTransactionObject using the following:

```jsx
for (let i = 0; i < allTxns.length; i++) {
  const trans = allTxns[i]
  if (trans.lsig) {
    let signedTxn = algosdk.signLogicSigTransactionObject(
      trans.unsignedTxn,
      trans.lsig
    )
    events.emit('sign-with-my-algo', {status: 'Signing Transactions...', progress: i, total: innerTxnsForSigning.length})
    trans.signedTxn = signedTxn.blob
  }
}
```

File: lib/send_assets.js [hunk 6]
```diff
@@ -66,35 +83,62 @@ const SendAssets = {
...
+            feeReceiverAddress
+          )
+        helper.packageUnsignedTransactions(
+          allTxns,
+          txnsForSigning,
+          toData.length,
+          outerSendTxn
+        )
       }
+      events.emit('sending-assets-event', { status: 'signing1' })
```
Comment (PhearZero) [inline lib/send_assets.js]: - [x] Unnecessary event, use 'sign-with-my-algo' events from `./helpers`

File: lib/send_assets.js [hunk 7]
```diff
@@ -7,25 +8,41 @@ const { convertCSVToArray } = require('convert-csv-to-array')
...
+      assetId,
+      amount,
+      fromAccount,
+      toAddress
     )
   },
   send: async function (assetId, fromAddress, csvInput) {
     try {
       const { algodClient, feeReceiverAddress } = helper.getAlgodex()
+      events.emit('sending-assets-event', { status: 'loading' })
```
Comment (PhearZero) [inline lib/send_assets.js]: - [x] Unnecessary event, we only need events from inside of each step and not the overall progress. Should be fired from `./helpers`

File: lib/send_assets.js [hunk 8]
```diff
@@ -66,35 +83,62 @@ const SendAssets = {
...
-
-      const confirmedTransactions = await helper.sendAllTransactions(signedAllTxns)
+      const confirmedTransactions = await helper.sendAllTransactions(
+        signedAllTxns
+      )
 
       let transResults = JSON.stringify(confirmedTransactions, null, 2)
       console.debug('trans results after confirmed are: ')
       console.debug(transResults)
+      events.emit('sending-assets-event', { status: 'complete' })
```
Comment (PhearZero) [inline lib/send_assets.js]: - [x] Unecissary event, needs to be inside of `sendAllTransactions` in `./helpers` to emit the actual status of sending transactions. The event can be called `send-all-transactions` and it should include the `total` and `progress` values in the payload

File: lib/send_assets.js [hunk 9]
```diff
@@ -66,35 +83,62 @@ const SendAssets = {
...
       return {
         error: false,
         confirmedTransactions,
       }
     } catch (error) {
+      events.emit('sending-assets-event', { status: 'stop' })
```
Comment (PhearZero) [inline lib/send_assets.js]: - [x] Unnecessary event, errors must be handled and `thrown` , revert this change until we have named Errors which we can `instanceof`

**Review by PhearZero — CHANGES_REQUESTED** [review]
Events are working but they can be leveraged to provide the actual data and not just an estimate. 

See the comments to extract the current progress from the inner helpers to the outer `useSendAsset` effect. 

- [x] Emit progress, status, and total for each step of the process
- [x] Remove any events from `send` since the `helpers` is the only place that needs them

File: components/SendAssetProgress.js (hunk 1 above)
Comment (treasurechic) [reply components/SendAssetProgress.js]: @PhearZero Everything is noted...I will fix 👍🏽

However, the event in send is actually necessary, it tells me when it is getting the balance and all(first step).
It also tells me when it is completed or failed especially when there is an error.(when to hide the progress).

**Review by stephclarkga — CHANGES_REQUESTED** [review]
I imagined that the progress bars would actually progress to show progress of each step since when sending to many wallets some of these steps can take a while so we need to give some active feedback. 
Right now it looks like the first step starts at 20% and never changes so it doesn't give the user much feedback. This bar should start from 0 and end full once this step is complete.
Second step is sending to the MyAlgo bridge and should also have a bar start at 0 and go full. (This step could be combined with the first progress bar if it takes less than about 4 seconds on average - I'm not sure what the time for this step really is but if someone knows that would be great)
Third step triggers the MyAlgo Signing UI and it'd be nice to have an indefinite loading bar on the site with the title "Awaiting Signature" title since this informs the customer that we are waiting on them.
Final step is sending the transactions with another progress bar that starts at 0 and ends full. It would be great if the number of transactions completed can be the label to the side of the bar (eg. 15/27 since this further confirms the number of transactions being sent - starts at 0/X and ends X/X instead of always out of 100)

**Comment by treasurechic** [comment]
> I imagined that the progress bars would actually progress to show progress of each step since when sending to many wallets some of these steps can take a while so we need to give some active feedback. Right now it looks like the first step starts at 20% and never changes so it doesn't give the user much feedback. This bar should start from 0 and end full once this step is complete. Second step is sending to the MyAlgo bridge and should also have a bar start at 0 and go full. (This step could be combined with the first progress bar if it takes less than about 4 seconds on average - I'm not sure what the time for this step really is but if someone knows that would be great) Third step triggers the MyAlgo Signing UI and it'd be nice to have an indefinite loading bar on the site with the title "Awaiting Signature" title since this informs the customer that we are waiting on them. Final step is sending the transactions with another progress bar that starts at 0 and ends full. It would be great if the number of transactions completed can be the label to the side of the bar (eg. 15/27 since this further confirms the number of transactions being sent - starts at 0/X and ends X/X instead of always out of 100)

Oh, I get that, I am working on that

File: lib/send_assets.js [hunk 10]
```diff
@@ -95,6 +135,9 @@ const SendAssets = {
         confirmedTransactions,
       }
     } catch (error) {
+      events.emit('Error', {
```
Comment (PhearZero) [inline lib/send_assets.js]: This emit can be removed and you can instance check the return value of `send`. You can also export the setters from `useSendAsset` for Inversion of Control.

Aside: The current error passing is an anti-pattern. We do not want to add more technical debt to it with an evented system. Refactor to use `instanceof` checking in the consumers of `send`

```jsx
//./hooks/useSendAsset

return  return { progress, status, total, hideProgress, setStatus, setHideProgress, setProgress }
``` 

```jsx
// ./pages/send-assets

 const { progress, status, total, hideProgress,  setStatus, setHideProgress, setProgress } = useSendAsset()

const responseData = await SendAssets.send(
  assetId,
  wallet,
  csvTransactions
)
      
if(responseData instanceof Error){
  setStatus('Sorry, an error has ocurred')
  setHideProgress(true)
}
```

File: components/LinearProgressWithLabel.js [hunk 11]
```diff
@@ -0,0 +1,41 @@
...
+import LinearProgress from '@mui/material/LinearProgress'
+import Typography from '@mui/material/Typography'
+import Box from '@mui/material/Box'
+import PropTypes from 'prop-types'
+
+export const LinearProgressWithLabel = (props) => {
+  const { status, progress, total, hideProgress } = props
+  return (
+    <>
+      {!hideProgress && (
```
Comment (PhearZero) [inline components/LinearProgressWithLabel.js:14]: - [x] LinearProgressWithLabel should always show a label and only hide the `<LinearProgress>` Box wrapper with `hideProgress`

Move hide progress to the `<LinearProgress>` component. This component would return an empty fragment which is not very useful. Hide this component from where it is being used based on the current state.

```jsx
// ./pages/send-assets
const hasStatusBar = useMemo(()=>{
    return typeof status !== 'undefined' // add move conditions
}, [status])

{ hasStatusBar && <LinearProgressWithLabel
  status={status}
  progress={progress}
  total={total}
  hideProgress={hideProgress}
/>}

```

**Review by PhearZero — CHANGES_REQUESTED** [review]
Everything looks good 🕺! Events and hooks look perfect. Two minor changes

- [x] Remove error emit
- [x] Always return an element from LinearProgressWithLabel

File: components/SendAssetProgress.js (hunk 1 above)
Comment (PhearZero) [reply components/SendAssetProgress.js]: We can remove the `send` emitters since JavaScript can natively handle the `Error` response of `send` without the need of events.

**Review by PhearZero — APPROVED** [review]
LGTM 🕺

**Comment by stephclarkga** [comment]
The progress bar is still loading weird for me (want to make sure I'm using the latest preview - let me know if this isn't the case!). Once I hit send and the bar comes up it starts at 75/100 (I think I saw 50/100 one time though) and the bar sits at that point so it's not very useful. Is there a way to show progress more consistently here?

And then when the MyAlgo popup comes up to sign, the progress bar should change to an indeterminate bar with a title "Awaiting Signature" to inform the user we are waiting on them. I'm not seeing this step at all anymore (I think I did before though but not sure)

And one other small thing - for the final step where it is sending, is it possible to have the label on the progress bar be "number of transactions sent/total" so for example if user is sending 48 transactions and it's halfway done, the label is at "24/48"? This reaffirms to the customer that everything was processed correctly

**Comment by treasurechic** [comment]
> The progress bar is still loading weird for me (want to make sure I'm using the latest preview - let me know if this isn't the case!). Once I hit send and the bar comes up it starts at 75/100 (I think I saw 50/100 one time though) and the bar sits at that point so it's not very useful. Is there a way to show progress more consistently here?
> 
> And then when the MyAlgo popup comes up to sign, the progress bar should change to an indeterminate bar with a title "Awaiting Signature" to inform the user we are waiting on them. I'm not seeing this step at all anymore (I think I did before though but not sure)
> 
> And one other small thing - for the final step where it is sending, is it possible to have the label on the progress bar be "number of transactions sent/total" so for example if user is sending 48 transactions and it's halfway done, the label is at "24/48"? This reaffirms to the customer that everything was processed correctly


@stephclarkga  The progress bar might look so fast if your network is really good. It actually starts from the beginning. The progress of the status is quite visible when you are sending to lots of addresses, like 6-8 addresses. If you need some, I can send you 8 addresses to test with.

"Waiting for user signature via the MyAlgo GUI" step has been added in as well. Here is the updated link to test again: https://algodex-mailbox-loqy1qtdr-algodex-dev.vercel.app/send-assets

**Comment by stephclarkga** [comment]
Thanks for confirming! I've tested with a list of 20 - I must just have good internet. Thanks!

**Review by stephclarkga — APPROVED** [review]
